deploy fixes

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -43,9 +43,9 @@ echo '\033[36mRestarting service\033[0m'
 cd
 if pkill -U $USER gunicorn
 then
-	echo '\033[31mKilling gunicorn failed!\033[0m'
-else
 	echo 'Success, probably.'
+else
+	echo '\033[31mKilling gunicorn failed!\033[0m'
 fi
 
 
@@ -60,4 +60,4 @@ diff -u /etc/systemd/system/webcli.service webcli.service || true
 echo
 echo '\033[36mChecking nginx configuration\033[0m'
 cd $HOME/app/system
-diff -u /etc/systemd/system/webcli.nginx /etc/nginx/sites-enabled/webcli || true
+diff -u /etc/nginx/sites-enabled/webcli webcli.nginx || true
