Improved deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -41,19 +41,23 @@ cd $HOME/app/webcli/
 echo
 echo '\033[36mRestarting service\033[0m'
 cd
-pkill -U $USER gunicorn
-echo 'Success, probably.'
+if pkill -U $USER gunicorn
+then
+	echo '\033[31mKilling gunicorn failed!\033[0m'
+else
+	echo 'Success, probably.'
+fi
 
 
 
 echo
 echo '\033[36mChecking systemd service file\033[0m'
 cd $HOME/app/system
-diff -u /etc/systemd/system/webcli.service webcli.service
+diff -u /etc/systemd/system/webcli.service webcli.service || true
 
 
 
 echo
 echo '\033[36mChecking nginx configuration\033[0m'
 cd $HOME/app/system
-diff -u /etc/systemd/system/webcli.nginx /etc/nginx/sites-enabled/webcli
+diff -u /etc/systemd/system/webcli.nginx /etc/nginx/sites-enabled/webcli || true
